import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    {
      type: "category",
      label: "Installation",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "General Information",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "general-info" }],
    },
    {
      type: "category",
      label: "Tools",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "tools" }],
    },
    { type: "autogenerated", dirName: "resources" },
  ],
  guidesSidebar: [
    {
      type: "category",
      label: "Daedalus",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "modding-basics-daedalus" }],
    },
    {
      type: "category",
      label: "Union",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "modding-basics-union" }],
    },
  ],
};

export default sidebars;
