import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebarsEncyclopedia: SidebarsConfig = {
  encyclopediaSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebarsEncyclopedia;
